# 国・地域の日本語表記（OWID entity名 → 日本語）
# 表示用の短い名前。グラフの凡例に収まる長さを優先。
JP = {
    "Afghanistan": "アフガニスタン",
    "Albania": "アルバニア",
    "Algeria": "アルジェリア",
    "American Samoa": "米領サモア",
    "Andorra": "アンドラ",
    "Angola": "アンゴラ",
    "Anguilla": "アンギラ",
    "Antigua and Barbuda": "アンティグア・バーブーダ",
    "Argentina": "アルゼンチン",
    "Armenia": "アルメニア",
    "Aruba": "アルバ",
    "Australia": "オーストラリア",
    "Austria": "オーストリア",
    "Azerbaijan": "アゼルバイジャン",
    "Bahamas": "バハマ",
    "Bahrain": "バーレーン",
    "Bangladesh": "バングラデシュ",
    "Barbados": "バルバドス",
    "Belarus": "ベラルーシ",
    "Belgium": "ベルギー",
    "Belize": "ベリーズ",
    "Benin": "ベナン",
    "Bermuda": "バミューダ",
    "Bhutan": "ブータン",
    "Bolivia": "ボリビア",
    "Bonaire Sint Eustatius and Saba": "ボネール等",
    "Bosnia and Herzegovina": "ボスニア・ヘルツェゴビナ",
    "Botswana": "ボツワナ",
    "Brazil": "ブラジル",
    "British Virgin Islands": "英領ヴァージン諸島",
    "Brunei": "ブルネイ",
    "Bulgaria": "ブルガリア",
    "Burkina Faso": "ブルキナファソ",
    "Burundi": "ブルンジ",
    "Cambodia": "カンボジア",
    "Cameroon": "カメルーン",
    "Canada": "カナダ",
    "Cape Verde": "カーボベルデ",
    "Cayman Islands": "ケイマン諸島",
    "Central African Republic": "中央アフリカ",
    "Chad": "チャド",
    "Chile": "チリ",
    "China": "中国",
    "Colombia": "コロンビア",
    "Comoros": "コモロ",
    "Congo": "コンゴ共和国",
    "Cook Islands": "クック諸島",
    "Costa Rica": "コスタリカ",
    "Cote d'Ivoire": "コートジボワール",
    "Croatia": "クロアチア",
    "Cuba": "キューバ",
    "Curacao": "キュラソー",
    "Cyprus": "キプロス",
    "Czechia": "チェコ",
    "Democratic Republic of Congo": "コンゴ民主共和国",
    "Denmark": "デンマーク",
    "Djibouti": "ジブチ",
    "Dominica": "ドミニカ国",
    "Dominican Republic": "ドミニカ共和国",
    "East Timor": "東ティモール",
    "Ecuador": "エクアドル",
    "Egypt": "エジプト",
    "El Salvador": "エルサルバドル",
    "Equatorial Guinea": "赤道ギニア",
    "Eritrea": "エリトリア",
    "Estonia": "エストニア",
    "Eswatini": "エスワティニ",
    "Ethiopia": "エチオピア",
    "Falkland Islands": "フォークランド諸島",
    "Faroe Islands": "フェロー諸島",
    "Fiji": "フィジー",
    "Finland": "フィンランド",
    "France": "フランス",
    "French Guiana": "仏領ギアナ",
    "French Polynesia": "仏領ポリネシア",
    "Gabon": "ガボン",
    "Gambia": "ガンビア",
    "Georgia": "ジョージア",
    "Germany": "ドイツ",
    "Ghana": "ガーナ",
    "Gibraltar": "ジブラルタル",
    "Greece": "ギリシャ",
    "Greenland": "グリーンランド",
    "Grenada": "グレナダ",
    "Guadeloupe": "グアドループ",
    "Guam": "グアム",
    "Guatemala": "グアテマラ",
    "Guernsey": "ガーンジー",
    "Guinea": "ギニア",
    "Guinea-Bissau": "ギニアビサウ",
    "Guyana": "ガイアナ",
    "Haiti": "ハイチ",
    "Honduras": "ホンジュラス",
    "Hong Kong": "香港",
    "Hungary": "ハンガリー",
    "Iceland": "アイスランド",
    "India": "インド",
    "Indonesia": "インドネシア",
    "Iran": "イラン",
    "Iraq": "イラク",
    "Ireland": "アイルランド",
    "Isle of Man": "マン島",
    "Israel": "イスラエル",
    "Italy": "イタリア",
    "Jamaica": "ジャマイカ",
    "Japan": "日本",
    "Jersey": "ジャージー",
    "Jordan": "ヨルダン",
    "Kazakhstan": "カザフスタン",
    "Kenya": "ケニア",
    "Kiribati": "キリバス",
    "Kosovo": "コソボ",
    "Kuwait": "クウェート",
    "Kyrgyzstan": "キルギス",
    "Laos": "ラオス",
    "Latvia": "ラトビア",
    "Lebanon": "レバノン",
    "Lesotho": "レソト",
    "Liberia": "リベリア",
    "Libya": "リビア",
    "Liechtenstein": "リヒテンシュタイン",
    "Lithuania": "リトアニア",
    "Luxembourg": "ルクセンブルク",
    "Macao": "マカオ",
    "Madagascar": "マダガスカル",
    "Malawi": "マラウイ",
    "Malaysia": "マレーシア",
    "Maldives": "モルディブ",
    "Mali": "マリ",
    "Malta": "マルタ",
    "Marshall Islands": "マーシャル諸島",
    "Martinique": "マルティニーク",
    "Mauritania": "モーリタニア",
    "Mauritius": "モーリシャス",
    "Mayotte": "マヨット",
    "Mexico": "メキシコ",
    "Micronesia (country)": "ミクロネシア",
    "Moldova": "モルドバ",
    "Monaco": "モナコ",
    "Mongolia": "モンゴル",
    "Montenegro": "モンテネグロ",
    "Montserrat": "モントセラト",
    "Morocco": "モロッコ",
    "Mozambique": "モザンビーク",
    "Myanmar": "ミャンマー",
    "Namibia": "ナミビア",
    "Nauru": "ナウル",
    "Nepal": "ネパール",
    "Netherlands": "オランダ",
    "New Caledonia": "ニューカレドニア",
    "New Zealand": "ニュージーランド",
    "Nicaragua": "ニカラグア",
    "Niger": "ニジェール",
    "Nigeria": "ナイジェリア",
    "Niue": "ニウエ",
    "North Korea": "北朝鮮",
    "North Macedonia": "北マケドニア",
    "Northern Mariana Islands": "北マリアナ諸島",
    "Norway": "ノルウェー",
    "Oman": "オマーン",
    "Pakistan": "パキスタン",
    "Palau": "パラオ",
    "Palestine": "パレスチナ",
    "Panama": "パナマ",
    "Papua New Guinea": "パプアニューギニア",
    "Paraguay": "パラグアイ",
    "Peru": "ペルー",
    "Philippines": "フィリピン",
    "Poland": "ポーランド",
    "Portugal": "ポルトガル",
    "Puerto Rico": "プエルトリコ",
    "Qatar": "カタール",
    "Reunion": "レユニオン",
    "Romania": "ルーマニア",
    "Russia": "ロシア",
    "Rwanda": "ルワンダ",
    "Saint Barthelemy": "サンバルテルミー",
    "Saint Helena": "セントヘレナ",
    "Saint Kitts and Nevis": "セントクリストファー・ネビス",
    "Saint Lucia": "セントルシア",
    "Saint Martin (French part)": "サン・マルタン",
    "Saint Pierre and Miquelon": "サンピエール島・ミクロン島",
    "Saint Vincent and the Grenadines": "セントビンセント",
    "Samoa": "サモア",
    "San Marino": "サンマリノ",
    "Sao Tome and Principe": "サントメ・プリンシペ",
    "Saudi Arabia": "サウジアラビア",
    "Senegal": "セネガル",
    "Serbia": "セルビア",
    "Seychelles": "セーシェル",
    "Sierra Leone": "シエラレオネ",
    "Singapore": "シンガポール",
    "Sint Maarten (Dutch part)": "シント・マールテン",
    "Slovakia": "スロバキア",
    "Slovenia": "スロベニア",
    "Solomon Islands": "ソロモン諸島",
    "Somalia": "ソマリア",
    "South Africa": "南アフリカ",
    "South Korea": "韓国",
    "South Sudan": "南スーダン",
    "Spain": "スペイン",
    "Sri Lanka": "スリランカ",
    "Sudan": "スーダン",
    "Suriname": "スリナム",
    "Svalbard and Jan Mayen": "スバールバル諸島",
    "Sweden": "スウェーデン",
    "Switzerland": "スイス",
    "Syria": "シリア",
    "Taiwan": "台湾",
    "Tajikistan": "タジキスタン",
    "Tanzania": "タンザニア",
    "Thailand": "タイ",
    "Togo": "トーゴ",
    "Tokelau": "トケラウ",
    "Tonga": "トンガ",
    "Trinidad and Tobago": "トリニダード・トバゴ",
    "Tunisia": "チュニジア",
    "Turkey": "トルコ",
    "Turkmenistan": "トルクメニスタン",
    "Turks and Caicos Islands": "タークス・カイコス諸島",
    "Tuvalu": "ツバル",
    "Uganda": "ウガンダ",
    "Ukraine": "ウクライナ",
    "United Arab Emirates": "アラブ首長国連邦",
    "United Kingdom": "イギリス",
    "United States": "アメリカ",
    "United States Virgin Islands": "米領ヴァージン諸島",
    "Uruguay": "ウルグアイ",
    "Uzbekistan": "ウズベキスタン",
    "Vanuatu": "バヌアツ",
    "Vatican": "バチカン",
    "Venezuela": "ベネズエラ",
    "Vietnam": "ベトナム",
    "Wallis and Futuna": "ウォリス・フツナ",
    "Western Sahara": "西サハラ",
    "Yemen": "イエメン",
    "Zambia": "ザンビア",
    "Zimbabwe": "ジンバブエ",
}

# 大陸・地域の集計（OWID の地域区分）
REGIONS = {
    "Africa": "アフリカ",
    "Asia": "アジア",
    "Europe": "ヨーロッパ",
    "North America": "北アメリカ",
    "South America": "南アメリカ",
    "Oceania": "オセアニア",
}

WORLD = {"World": "世界全体"}
